name: Deploy to Vercel (Preview)

on:
  push:
    branches:
      - preview

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build and Deploy to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
